name: goreleaser

on:
  push:
    tags: ['a/v*', 'b/v*']

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - if: contains(github.ref, "a/v")
        shell: bash
        run: echo "-f ./a/.goreleaser.yml" >> $GITHUB_ENV
      - if: contains(github.ref, "b/v")
        shell: bash
        run: echo "-f ./b/.goreleaser.yml" >> $GITHUB_ENV
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
